--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: EventDescriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EventDescriptions" (
    "Id" bigint NOT NULL,
    "EventId" bigint NOT NULL,
    "Description" text NOT NULL
);


ALTER TABLE public."EventDescriptions" OWNER TO postgres;

--
-- Name: EventDescriptions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EventDescriptions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EventDescriptions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Events" (
    "Id" bigint NOT NULL,
    "Name" text NOT NULL,
    "Date" date NOT NULL,
    "Category" text NOT NULL
);


ALTER TABLE public."Events" OWNER TO postgres;

--
-- Name: Events_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Events" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Events_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: EventDescriptions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."EventDescriptions" ("Id", "EventId", "Description") FROM stdin;
11	22	Desc 2
13	24	Создать вторую таблицу и сделать join таблиц
12	23	Desc 3
14	25	Разработать календарь событий на asp.net core
15	26	Доработать календарь событий
10	21	Desc 1 !
16	27	Просто отдохнуть
17	28	Записать видео для пояснения кода
\.


--
-- Data for Name: Events; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Events" ("Id", "Name", "Date", "Category") FROM stdin;
22	Test 2	2024-05-06	Работа
24	Тестовое задание	2024-05-06	Работа
23	Test 3	2024-05-08	Здоровье
25	Тестовое задание	2024-05-04	Личное
26	Тестовое задание	2024-05-05	Домашние дела
21	Test 1 !	2024-05-05	Праздники
27	Отдых	2024-06-01	Праздники
28	Тестовое задание	2024-05-06	Личное
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240503171854_Init	8.0.4
20240506072424_EventDescription	8.0.4
\.


--
-- Name: EventDescriptions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EventDescriptions_Id_seq"', 22, true);


--
-- Name: Events_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Events_Id_seq"', 33, true);


--
-- Name: EventDescriptions PK_EventDescriptions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EventDescriptions"
    ADD CONSTRAINT "PK_EventDescriptions" PRIMARY KEY ("Id");


--
-- Name: Events PK_Events; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Events"
    ADD CONSTRAINT "PK_Events" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- PostgreSQL database dump complete
--

